spring:
  application:
    name: resume-analyzer
  datasource:
    url: jdbc:postgresql://localhost:5432/vector_db
    username: postgres
    password: postgres
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3
      embedding:
        options:
          model: nomic-embed-text
    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 768